[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"

[fmt]
int_types = "short"
multiline_func_header = "params_first"
